pip install shapely
pip install pyyaml
pip install scipy
pip install easydict
pip install tensorboardX
pip install mpi4py==2.0.0
pip install gaft
pip install opencv-python==4.1.0.25
pip install numpy==1.12.1
pip install hyperopt
pip install ray==0.6.3
pip install requests